apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-acc-deploy
  namespace: iris-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-for-serviceaccount
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-serviceaccount
  namespace: iris-ns
subjects:
  - kind: ServiceAccount
    name: service-acc-deploy
    namespace: iris-ns
roleRef:
  kind: ClusterRole
  name: role-for-serviceaccount
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  namespace: iris-ns
  name: sa-secret
  annotations:
    kubernetes.io/service-account.name: "service-acc-deploy"
---

