apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-ui
  namespace: iris-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris-ui
  template:
    metadata:
      labels:
        app: iris-ui
    spec:
      containers:
      - name: iris-ui
        image: irissouthindia.azurecr.io/iris/iris-ui:nightly
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
